BEGIN TRANSACTION;

INSERT INTO users (email,first_name,last_name,password_hash,role) VALUES ('user3@gmail.org', 'User', 'Thee', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (email,first_name,last_name,password_hash,role) VALUES ('user4@gmail.org', 'User', 'Four', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (email,first_name,last_name,password_hash,role) VALUES ('user5@gmail.org', 'User', 'Five', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (email,first_name,last_name,password_hash,role) VALUES ('user6@gmail.org', 'User', 'Six', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (email,first_name,last_name,password_hash,role) VALUES ('user7@gmail.org', 'User', 'Seven', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (email,first_name,last_name,password_hash,role) VALUES ('user8@gmail.org', 'User', 'Eight', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (email,first_name,last_name,password_hash,role) VALUES ('user9@gmail.org', 'User', 'Nine', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (email,first_name,last_name,password_hash,role) VALUES ('user10@gmail.org', 'User', 'Ten', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (email,first_name,last_name,password_hash,role) VALUES ('user11@gmail.org', 'User', 'Eleven', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (email,first_name,last_name,password_hash,role) VALUES ('user12@gmail.org', 'User', 'Twelve', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (email,first_name,last_name,password_hash,role) VALUES ('user13@gmail.org', 'User', 'Thirteen', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (email,first_name,last_name,password_hash,role) VALUES ('user14@gmail.org', 'User', 'Fourteen', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (email,first_name,last_name,password_hash,role) VALUES ('user15@gmail.org', 'User', 'Fifteen', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (email,first_name,last_name,password_hash,role) VALUES ('user16@gmail.org', 'User', 'Sixteen', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (email,first_name,last_name,password_hash,role) VALUES ('user17@gmail.org', 'User', 'Seventeen', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (email,first_name,last_name,password_hash,role) VALUES ('user18@gmail.org', 'User', 'Eighteen', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (email,first_name,last_name,password_hash,role) VALUES ('user19@gmail.org', 'User', 'Nineteen', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (email,first_name,last_name,password_hash,role) VALUES ('user20@gmail.org', 'User', 'Twenty', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (email,first_name,last_name,password_hash,role) VALUES ('user21@gmail.org', 'User', 'Twenty-one', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (email,first_name,last_name,password_hash,role) VALUES ('user22@gmail.org', 'User', 'Twenty-two', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (email,first_name,last_name,password_hash,role) VALUES ('user23@gmail.org', 'User', 'Twenty-three', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (email,first_name,last_name,password_hash,role) VALUES ('user24@gmail.org', 'User', 'Twenty-four', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (email,first_name,last_name,password_hash,role) VALUES ('user25@gmail.org', 'User', 'Twenty-five', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (email,first_name,last_name,password_hash,role) VALUES ('user26@gmail.org', 'User', 'Twenty-six', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (email,first_name,last_name,password_hash,role) VALUES ('user27@gmail.org', 'User', 'Twenty-seven', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (email,first_name,last_name,password_hash,role) VALUES ('user28@gmail.org', 'User', 'Twenty-eight', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (email,first_name,last_name,password_hash,role) VALUES ('user29@gmail.org', 'User', 'Twenty-nine', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (email,first_name,last_name,password_hash,role) VALUES ('user30@gmail.org', 'User', 'Thirty', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (email,first_name,last_name,password_hash,role) VALUES ('user31@gmail.org', 'User', 'Thirty-one', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (email,first_name,last_name,password_hash,role) VALUES ('user32@gmail.org', 'User', 'Thirty-two', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (email,first_name,last_name,password_hash,role) VALUES ('user33@gmail.org', 'User', 'Thirty-three', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (email,first_name,last_name,password_hash,role) VALUES ('user34@gmail.org', 'User', 'Thirty-four', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (email,first_name,last_name,password_hash,role) VALUES ('user35@gmail.org', 'User', 'Thirty-five', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (email,first_name,last_name,password_hash,role) VALUES ('user36@gmail.org', 'User', 'Thirty-six', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (email,first_name,last_name,password_hash,role) VALUES ('user37@gmail.org', 'User', 'Thirty-seven', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');


INSERT INTO user_restrictions (user_id, restriction_id) VALUES (1001, 2001), (1001, 2002), (1001, 2008);

INSERT INTO pluck (pluck_name, pluck_description, pluck_date_time, pluck_place, pluck_banner) VALUES ('Happy Birthday, June!', 'Bring your favorite dishes to celebrate her big day!', '2022-09-03 17:30:00', '1242 Lathrop Way. Arnoldsburg, XX 12345', 'https://cdn.discordapp.com/attachments/965635046734168084/1009516049747681411/pink_bubbles.png');
INSERT INTO pluck (pluck_name, pluck_description, pluck_date_time, pluck_place, pluck_banner) VALUES ('BYOD!', 'I am hungry and do not feel like cooking. Bring me your best snacks!', '2022-09-10 18:00:00', '1566 Poplar Rd. Trainsville, XX 12345', 'https://cdn.discordapp.com/attachments/965635046734168084/1009516050318102588/pool_party.png');
INSERT INTO pluck (pluck_name, pluck_description, pluck_date_time, pluck_place, pluck_banner) VALUES ('Dave and Linus, 10 years strong!', 'Dave and Linus are celebrating ten years! Bring a fancy drink and a dish to wish them well.', '2022-09-17 19:30:00', '5681 Nautilus Ave. Plainton, XX 12345', 'https://cdn.discordapp.com/attachments/965635046734168084/1009516049122725898/confetti_ribbons.png');

INSERT INTO pluck_cat (pluck_id, cat_id, cat_limit) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'Happy Birthday, June!'), (SELECT cat_id FROM category WHERE cat_name = 'sides & snacks'), 6);
INSERT INTO pluck_cat (pluck_id, cat_id, cat_limit) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'Happy Birthday, June!'), (SELECT cat_id FROM category WHERE cat_name = 'main dishes'), 6);
INSERT INTO pluck_cat (pluck_id, cat_id, cat_limit) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'Happy Birthday, June!'), (SELECT cat_id FROM category WHERE cat_name = 'drinks'), 6);
INSERT INTO pluck_cat (pluck_id, cat_id, cat_limit) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'Happy Birthday, June!'), (SELECT cat_id FROM category WHERE cat_name = 'desserts'), 6);
INSERT INTO pluck_cat (pluck_id, cat_id, cat_limit) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'Happy Birthday, June!'), (SELECT cat_id FROM category WHERE cat_name = 'utensils, etc.'), 6);
INSERT INTO pluck_cat (pluck_id, cat_id, cat_limit) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'BYOD!'), (SELECT cat_id FROM category WHERE cat_name = 'sides & snacks'), 10);
INSERT INTO pluck_cat (pluck_id, cat_id, cat_limit) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'BYOD!'), (SELECT cat_id FROM category WHERE cat_name = 'drinks'), 4);
INSERT INTO pluck_cat (pluck_id, cat_id, cat_limit) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'BYOD!'), (SELECT cat_id FROM category WHERE cat_name = 'desserts'), 3);
INSERT INTO pluck_cat (pluck_id, cat_id, cat_limit) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'Dave and Linus, 10 years strong!'), (SELECT cat_id FROM category WHERE cat_name = 'sides & snacks'), 5);
INSERT INTO pluck_cat (pluck_id, cat_id, cat_limit) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'Dave and Linus, 10 years strong!'), (SELECT cat_id FROM category WHERE cat_name = 'main dishes'), 3);
INSERT INTO pluck_cat (pluck_id, cat_id, cat_limit) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'Dave and Linus, 10 years strong!'), (SELECT cat_id FROM category WHERE cat_name = 'drinks'), 8);


INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'Happy Birthday, June!'), (SELECT cat_id FROM category WHERE cat_name = 'sides & snacks'), 1001, 'veggie plate', 12, 'carrots, celery sticks, tomatoes, brocolli, and ranch', 'Brant');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'Happy Birthday, June!'), (SELECT cat_id FROM category WHERE cat_name = 'sides & snacks'), 1002, 'spinach puffs', 10, 'creamy spinach wrapped in fluffy warm pastry', 'Luke');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'Happy Birthday, June!'), (SELECT cat_id FROM category WHERE cat_name = 'sides & snacks'), 1003, 'pigs in a blanket', 20, 'you know em, you love em.', 'Grunkle Stan');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'Happy Birthday, June!'), (SELECT cat_id FROM category WHERE cat_name = 'main dishes'), 1004, 'lasagna', 12, 'Grandmas recipe and Junes favorite!', 'Jimothy');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'Happy Birthday, June!'), (SELECT cat_id FROM category WHERE cat_name = 'main dishes'), 1005, 'fajita bake', 10, 'served with warm tortillas and fresh toppings!', 'Hubert');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'Happy Birthday, June!'), (SELECT cat_id FROM category WHERE cat_name = 'main dishes'), 1006, 'pot pie', 10, 'creamy comfort food with a flaky crust', 'Ignacio');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'Happy Birthday, June!'), (SELECT cat_id FROM category WHERE cat_name = 'drinks'), 1007, 'hard cider', 24, 'Angry Orchard variety pack', 'Harold');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'Happy Birthday, June!'), (SELECT cat_id FROM category WHERE cat_name = 'drinks'), 1008, 'soda', 24, 'im bringing a little bit of everything.', 'Betty');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'Happy Birthday, June!'), (SELECT cat_id FROM category WHERE cat_name = 'drinks'), 1009, 'sangria', 12, 'I will not be driving, so its gonna be strong yall', 'The Chosen One');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'Happy Birthday, June!'), (SELECT cat_id FROM category WHERE cat_name = 'desserts'), 1010, 'oreo pie', 8, 'I will not be taking leftovers home, so gobble up', 'Susan');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'Happy Birthday, June!'), (SELECT cat_id FROM category WHERE cat_name = 'desserts'), 1011, 'apple crumble', 10, 'Found a new recipe so youll be my guinea pigs', 'Tammy');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'Happy Birthday, June!'), (SELECT cat_id FROM category WHERE cat_name = 'desserts'), 1012, 'turnovers', 24, 'flavors will be apple, cherry, and peach', 'Mom');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'Happy Birthday, June!'), (SELECT cat_id FROM category WHERE cat_name = 'utensils, etc.'), 1013, 'flatware', 36, '.', 'Patty');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'Happy Birthday, June!'), (SELECT cat_id FROM category WHERE cat_name = 'utensils, etc.'), 1013, 'plates', 36, '.', 'Patty');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'Happy Birthday, June!'), (SELECT cat_id FROM category WHERE cat_name = 'utensils, etc.'), 1013, 'napkins', 36, '.', 'Patty');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'BYOD!'), (SELECT cat_id FROM category WHERE cat_name = 'sides & snacks'), 1014, 'pigs in a blanket', 12, 'teeny weenies', 'Seth');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'BYOD!'), (SELECT cat_id FROM category WHERE cat_name = 'sides & snacks'), 1015, 'pizza rolls', 12, 'im bringing like 6 bags idk', 'Lonnie');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'BYOD!'), (SELECT cat_id FROM category WHERE cat_name = 'sides & snacks'), 1016, 'loaded tots', 10, 'tasty recipes for just such an occasion', 'Richard');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'BYOD!'), (SELECT cat_id FROM category WHERE cat_name = 'sides & snacks'), 1017, 'dumplings', 20, 'my mom made way too many so im bringing them', 'Alan');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'BYOD!'), (SELECT cat_id FROM category WHERE cat_name = 'sides & snacks'), 1018, 'beef nacho dip', 12, 'probably serves more than that but im gonna eat like half of it so', 'Lemmy');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'BYOD!'), (SELECT cat_id FROM category WHERE cat_name = 'sides & snacks'), 1019, 'buffalo dip', 10, 'all your daily values of dairy for the day.', 'Precious');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'BYOD!'), (SELECT cat_id FROM category WHERE cat_name = 'sides & snacks'), 1020, 'mac & cheese', 8, 'classic baked', 'Hammond');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'BYOD!'), (SELECT cat_id FROM category WHERE cat_name = 'drinks'), 1021, 'Mountain Dew', 12, 'Code Red, regular, and whatever else i can find as 2 liters.', 'Randall');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'BYOD!'), (SELECT cat_id FROM category WHERE cat_name = 'drinks'), 1022, 'pepsi', 20, 'bringing a bunch', 'Sarah');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'BYOD!'), (SELECT cat_id FROM category WHERE cat_name = 'drinks'), 1023, 'beer', 36, 'i am bringing 36 servings of beer. :P', 'Jeremy');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'BYOD!'), (SELECT cat_id FROM category WHERE cat_name = 'drinks'), 1024, 'wine coolers', 24, 'they only cost a dollar so I went a little nuts.', 'Phil');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'BYOD!'), (SELECT cat_id FROM category WHERE cat_name = 'desserts'), 1025, 'drumsticks', 24, 'a huge box of ice cream cones with nuts and chocolate', 'Helen');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'BYOD!'), (SELECT cat_id FROM category WHERE cat_name = 'desserts'), 1026, 'cake', 8, 'chocolate with chocolate icing', 'Jane');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'Dave and Linus, 10 years strong!'), (SELECT cat_id FROM category WHERE cat_name = 'sides & snacks'), 1027, 'mini quiches', 12, 'cute, tiny, delicious.', 'Mina');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'Dave and Linus, 10 years strong!'), (SELECT cat_id FROM category WHERE cat_name = 'sides & snacks'), 1028, 'creamed spinach', 10, 'my moms recipe, a perfect side.', 'Lily');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'Dave and Linus, 10 years strong!'), (SELECT cat_id FROM category WHERE cat_name = 'sides & snacks'), 1029, 'Hatties famous dip', 16, 'we all know and love this recipe and I will be bringing it!', 'Colin');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'Dave and Linus, 10 years strong!'), (SELECT cat_id FROM category WHERE cat_name = 'main dishes'), 1030, 'chicken marsala', 12, 'delicious chicken with marsala wine, cooked to perfection', 'Andre');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'Dave and Linus, 10 years strong!'), (SELECT cat_id FROM category WHERE cat_name = 'main dishes'), 1031, 'beef tips', 10, 'red wine glaze and fresh herbs', 'Peter');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'Dave and Linus, 10 years strong!'), (SELECT cat_id FROM category WHERE cat_name = 'main dishes'), 1032, 'garlic ginger tofu', 8, 'I am bringing rice to have on the side!', 'Terry');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'Dave and Linus, 10 years strong!'), (SELECT cat_id FROM category WHERE cat_name = 'drinks'), 1033, 'sangria', 12, 'extra orange!', 'Delia');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'Dave and Linus, 10 years strong!'), (SELECT cat_id FROM category WHERE cat_name = 'drinks'), 1034, 'mimosas', 16, '.', 'Perry');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'Dave and Linus, 10 years strong!'), (SELECT cat_id FROM category WHERE cat_name = 'drinks'), 1035, 'bellinis', 16, 'peach juice and champers!', 'Felix');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'Dave and Linus, 10 years strong!'), (SELECT cat_id FROM category WHERE cat_name = 'drinks'), 1036, 'wine', 10, 'some red, some white, and some rose', 'Remus');
INSERT INTO pluck_dish (pluck_id, cat_id, user_id, dish_name, servings, description, username) VALUES ((SELECT pluck_id FROM pluck WHERE pluck_name = 'Dave and Linus, 10 years strong!'), (SELECT cat_id FROM category WHERE cat_name = 'drinks'), 1037, 'juice', 24, 'a little bit of everything!', 'Danya');

INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3001, 1001, 'host');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3001, 1002, 'guest');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3001, 1003, 'guest');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3001, 1004, 'guest');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3001, 1005, 'guest');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3001, 1006, 'guest');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3001, 1007, 'guest');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3001, 1008, 'guest');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3001, 1009, 'guest');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3001, 1010, 'guest');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3001, 1011, 'guest');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3001, 1012, 'guest');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3001, 1013, 'guest');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3002, 1014, 'host');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3002, 1015, 'guest');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3002, 1016, 'guest');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3002, 1017, 'guest');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3002, 1018, 'guest');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3002, 1019, 'guest');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3002, 1020, 'guest');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3002, 1021, 'guest');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3002, 1022, 'guest');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3002, 1023, 'guest');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3002, 1024, 'guest');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3002, 1025, 'guest');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3002, 1026, 'guest');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3003, 1027, 'host');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3003, 1028, 'guest');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3003, 1029, 'guest');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3003, 1030, 'guest');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3003, 1031, 'guest');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3003, 1032, 'guest');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3003, 1033, 'guest');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3003, 1034, 'guest');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3003, 1035, 'guest');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3003, 1036, 'guest');
INSERT INTO pluck_user (pluck_id, user_id, pluck_role) VALUES (3003, 1037, 'guest');

INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4001, 2001), (4001, 2002), (4001, 2003), (4001, 2004), (4001, 2005), (4001, 2006), (4001, 2007), (4001, 2008);
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4002, 2003), (4002, 2004), (4002, 2006), (4002, 2008);
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4003, 2001), (4003, 2006);
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4004, 2006);
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4005, 2001), (4005, 2003), (4005, 2004), (4005, 2006);
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4006, 2006);
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4007, 2001), (4007, 2002), (4007, 2004), (4007, 2006), (4007, 2007), (4007, 2008);
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4008, 2001), (4008, 2002), (4008, 2003), (4008, 2004), (4008, 2005), (4008, 2006), (4008, 2007), (4008, 2008);
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4009, 2001), (4009, 2002), (4009, 2004), (4009, 2006), (4009, 2007), (4009, 2008);
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4010, 2006), (4010, 2008);
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4011, 2003), (4011, 2004), (4011, 2006), (4011, 2008);
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4012, 2003), (4012, 2004), (4012, 2006), (4012, 2008);
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4013, 2001), (4013, 2002), (4013, 2003), (4013, 2004), (4013, 2005), (4013, 2006), (4013, 2007), (4013, 2008);
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4014, 2001), (4014, 2002), (4014, 2003), (4014, 2004), (4014, 2005), (4014, 2006), (4014, 2007), (4014, 2008); 
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4015, 2001), (4015, 2002), (4015, 2003), (4015, 2004), (4015, 2005), (4015, 2006), (4015, 2007), (4015, 2008); 
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4016, 2001), (4016, 2006);
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4017, 2006);
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4018, 2006);
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4020, 2006);
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4021, 2006);
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4022, 2006), (4022, 2008);
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4023, 2006), (4023, 2003), (4023, 2004), (4023, 2007), (4023, 2008);
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4024, 2006), (4024, 2003), (4024, 2004), (4024, 2007), (4024, 2008);
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4025, 2006), (4025, 2007), (4025, 2008);
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4026, 2006), (4026, 2007), (4026, 2008);
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4027, 2008);
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4028, 2003), (4028, 2004), (4028, 2008);
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4029, 2003), (4029, 2004), (4029, 2006), (4029, 2008);
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4030, 2003), (4030, 2004), (4030, 2006), (4030, 2008);
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4031, 2003), (4031, 2004), (4031, 2006), (4031, 2008);
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4032, 2001), (4032, 2004), (4032, 2006);
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4033, 2001), (4033, 2002), (4033, 2006);
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4034, 2001), (4034, 2003), (4034, 2004), (4034, 2007), (4034, 2008);
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4035, 2001), (4035, 2002), (4035, 2004), (4035, 2006), (4035, 2007), (4035, 2008);
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4036, 2001), (4036, 2002), (4036, 2004), (4036, 2006), (4036, 2007), (4036, 2008);
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4037, 2001), (4037, 2002), (4037, 2004), (4037, 2006), (4037, 2007), (4037, 2008);
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4038, 2001), (4038, 2002), (4038, 2004), (4038, 2006), (4038, 2007), (4038, 2008);
INSERT INTO dish_restrictions (dish_id, restriction_id) VALUES (4039, 2001), (4039, 2002), (4039, 2003), (4039, 2004), (4039, 2006), (4039, 2007), (4039, 2008);

COMMIT TRANSACTION;