SELECT * FROM users;
SELECT * FROM restrictions;
SELECT * FROM user_restrictions;
SELECT * FROM pluck;
SELECT * FROM pluck_dish;
SELECT * FROM category;
SELECT * FROM pluck_cat;
SELECT * FROM pluck_user;
SELECT * FROM dish_restrictions;